name: Front-Build-To-Server2

on:
  push:
    branches: [feature/front]

jobs:
  deploy:
    name: Build, Deploy to S3 bucket
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [12.16.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: yarn
        working-directory: "frontend/"

      - name: yarn build
        run: yarn build
        working-directory: "frontend/"
        env:
          CI: ""

      - name: Deploy to Server(Naver2)
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HACKDAY_SERVER2_SSH }}
          ARGS: "-rltgoDzvO"
          SOURCE: "frontend/build"
          REMOTE_HOST: "27.96.130.172"
          REMOTE_USER: "root"
          REMOTE_PORT: "22"
          TARGET: "/root/test/"

      - name: LOVE HACKDAY
        run: "done"
