name: Front-Build-To-NaverServer2

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Build & Deploy(Copy to Server)
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [12.16.x]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: yarn
        working-directory: "frontend/"

      - name: yarn build
        run: yarn build
        working-directory: "frontend/"
        env:
          CI: ""

      - name: Deploy to Server(Naver2)
        uses: appleboy/scp-action@master
        with:
          host: "27.96.130.172"
          port: "22"
          username: "root"
          key: ${{ secrets.HACKDAY_SERVER2_SSH }}
          source: "frontend/build"
          target: "/root/test"
          rm: true

      - name: LOVE HACKDAY
        run: echo done
